### ISSUE TITLE
Fix Emoji Button Functionality on Card Creation Page

### ISSUE THREAD

**Issue by VanshChitransh** [nfoert/cardie#59] opened 2024-10-01 20:09 UTC
#### Description:
On the card creation page of the website, the "Add Emoji" button is not functioning as expected. When users click on the button, it does not display any actual emojis, which hinders the ability to enhance the text with emojis. This issue affects the overall user experience and limits the functionality of the card creation feature.

#### Steps to Reproduce:
1. Navigate to the card creation page.
2. Add some text to the card.
3. Click on the "Add Emoji" button.
4. Observe that no actual emojis are displayed.

#### Expected Behavior:
Clicking the "Add Emoji" button should display a selection of emojis for the user to choose from, allowing them to enhance their card content.

#### Actual Behavior:
No emojis are displayed when the "Add Emoji" button is clicked.

#### Screenshot:
![Screenshot from 2024-10-02 01-36-45](https://github.com/user-attachments/assets/68ce2b0a-fa72-49ab-94b7-5229a2095d10)

#### Priority:
High

#### Suggested Solution:
- Investigate the implementation of the "Add Emoji" button to ensure it correctly retrieves and displays emojis.
- Ensure compatibility with the emoji library or API being used.
- Perform testing across different devices and browsers to confirm functionality.

#### Additional Information:
- **Browser/OS:** [List of browsers/operating systems where the issue was observed]
- **Version:** [Version of the application or website]

**Comment by VanshChitransh** [comment] 2024-10-01 20:13
@nfoert I would like to work on it.

**Comment by nfoert** [comment] 2024-10-02 01:17
Duplicate of #21, may have been fixed in #52.

**Closed by nfoert** 2024-10-02 01:17 UTC
